test: validate manage singularity/enroot cache works (#911)

diff --git a/.circleci/real_config.yml b/.circleci/real_config.yml
--- a/.circleci/real_config.yml
+++ b/.circleci/real_config.yml
@@ -2460,9 +2460,35 @@ jobs:
             # Cleanup podman state from any issues in prior runs
             #sudo su - launcher -c "pdsh -R ssh -w znode50,znode51,znode53,znode54 XDG_RUNTIME_DIR=/tmp/launcher_podman podman system migrate" || true
             sinfo -R
-            sudo su - launcher -c "/etc/launcher/scripts/manage-singularity-cache --cuda --cpu <<pipeline.parameters.default-pt-gpu-image>>" || true
-            sudo su - launcher -c "ENROOT_RUNTIME_PATH=/tmp/launcher /etc/launcher/scripts/manage-enroot-cache -s /lustre/ssd/foundation_engineering/ --cuda --cpu <<pipeline.parameters.default-pt-gpu-image>>" || true
 
+      - run:
+          name: Download Apptainer/Enroot image
+          command: |
+            if sudo su - launcher -c "/etc/launcher/scripts/manage-singularity-cache --cuda --cpu --rocm <<pipeline.parameters.default-pt-gpu-image>>"; then
+                echo "Downloaded Singularity image <<pipeline.parameters.default-pt-gpu-image>> "
+            else
+                EXIT_STATUS=$?
+                echo "Failed downloading Singularity image. Received exit code $EXIT_STATUS"
+                #Ignore the other failures except for IMAGE_REF_NOT_FOUND_IN_DOC=18 or DOC_FILE_NOT_FOUND=11
+                if [[ $EXIT_STATUS -eq 18 || $EXIT_STATUS -eq 11 ]]; then
+                    exit $EXIT_STATUS
+                else
+                    exit 0
+                fi
+            fi
+            if sudo su - launcher -c "ENROOT_RUNTIME_PATH=/tmp/launcher /etc/launcher/scripts/manage-enroot-cache -s /lustre/ssd/foundation_engineering/ --cuda --cpu --rocm <<pipeline.parameters.default-pt-gpu-image>>"; then
+                echo "Downloaded Enroot image <<pipeline.parameters.default-pt-gpu-image>> "
+            else
+                EXIT_STATUS=$?
+                echo "Failed downloading Enroot image. Received exit code $EXIT_STATUS"
+                #Ignore the other failures except for IMAGE_REF_NOT_FOUND_IN_DOC=18 or DOC_FILE_NOT_FOUND=11
+                if [[ $EXIT_STATUS -eq 18 || $EXIT_STATUS -eq 11 ]]; then
+                    exit $EXIT_STATUS
+                else
+                    exit 0
+                fi
+            fi
+      
       - wait-for-master:
           host: localhost
 
