ci: [FE-228] Enable test-e2e-slurm-agent-singularity-znode to delay when resources are not available (#1105)
* chore: changed slot query to jobname query and extended time

* chore: changed time to 30minute timeout and added test for running

* added squeue query to gcp agent test

* fix: added gcloud ssh command

* fix: added zone definition

* fix: added escape character and simplified squeue command

* fix: removed name for srun

* chore: changed job name to be accurate

* chore: readded slot query

* chore: fix rebase

* chore: fix config.yml and real_config.yaml

* fix: fixed overwrite

* fix: fix config.yml and real_config.yml differences

diff --git a/.circleci/real_config.yml b/.circleci/real_config.yml
--- a/.circleci/real_config.yml
+++ b/.circleci/real_config.yml
@@ -2264,12 +2264,34 @@ jobs:
                   srun determined-agent --master-host=<<parameters.master-host>> --master-port=<<parameters.master-port>> --resource-pool=default --container-runtime=<<parameters.container-run-type>>
                 background: true
             - run: 
+                name: Query the job to ensure Determined Agent is running
+                command: |
+                  # 60 tries gives 30 minutes of tries until the query times out
+                  tries=60
+                  # squeue command gives name and state information. There must be an escape character for the gcloud command.
+                  ZONE=$(terraform -chdir=tools/slurm/terraform output --raw zone)
+                  INSTANCE_NAME=$(terraform -chdir=tools/slurm/terraform output --raw instance_name)
+                  PROJECT=$(terraform -chdir=tools/slurm/terraform output --raw project)
+                  gcloud compute ssh --zone "$ZONE" "$INSTANCE_NAME" --project "$PROJECT" -- squeue -o "%j\ %T"
+                  # Queries until the jobname is shown in a running state. The agent job must be running to run e2e tests
+                  until [[ -n $(gcloud compute ssh --zone "$ZONE" "$INSTANCE_NAME" --project "$PROJECT" -- squeue -o "%j\ %T" | grep "determined-agent" | grep "RUNNING") ]] ; do
+                      if [[ $((--tries)) -eq 0 ]]; then
+                        echo "The job determined-agent did not start. Please check if there are other jobs in the queue preventing this job from starting"
+                        exit 1
+                      fi
+                      echo "Waiting 30s to query for the job name again..."
+                      sleep 30
+                      echo "Retrying job query..."
+                      gcloud compute ssh --zone "$ZONE" "$INSTANCE_NAME" --project "$PROJECT" -- squeue -o "%j\ %T"
+                  done
+            - run: 
                 name: Query the slot count to ensure slots are allocated
                 command: |
                   tries=20
                   det slot list
                   until [[ $(det slot list | wc -l) -gt 2 ]] ; do
                       if [[ $((--tries)) -eq 0 ]]; then
+                        echo "ERROR: determined-agent failed to register at least 2 slots. Check the 'Transfer and Allocate agent resources on VM' for any failures."
                         exit 1
                       fi
                       echo "Waiting 5s to query slots again..."
@@ -2581,12 +2603,30 @@ jobs:
                   --master-host=$MASTER_HOST  --master-port=$MASTER_PORT --resource-pool=default --container-runtime=singularity  --slot-type=cuda
                 background: true
             - run: 
+                name: Query the job to ensure Determined Agent is running
+                command: |
+                  # 60 tries gives 30 minutes of tries until the query times out
+                  tries=60
+                  squeue -u launcher -o "%j %T"
+                  # Queries until the jobname is shown in a running state. The agent job must be running to run e2e tests
+                  until [[ -n $(squeue -u launcher -o "%j %T" | grep "determined-agent-$HOSTNAME" | grep "RUNNING") ]] ; do
+                      if [[ $((--tries)) -eq 0 ]]; then
+                        echo "The job determined-agent-$HOSTNAME did not start. Please check if there are jobs in the queue preventing this job from starting"
+                        exit 1
+                      fi
+                      echo "Waiting 30s to query for the job name again..."
+                      sleep 30
+                      echo "Retrying job query..."
+                      squeue -u launcher -o "%j %T"
+                  done
+            - run: 
                 name: Query the slot count to ensure slots are allocated
                 command: |
                   tries=20
                   det slot list
                   until [[ $(det slot list | wc -l) -gt 2 ]] ; do
                       if [[ $((--tries)) -eq 0 ]]; then
+                        echo "ERROR: determined-agent failed to register at least 2 slots. Check the 'Transfer and Allocate agent resources on VM' for any failures."
                         exit 1
                       fi
                       echo "Waiting 5s to query slots again..."
