fix cluster wait check
otherwise it doesn't fail after waiting for max iters

diff --git a/.circleci/real_config.yml b/.circleci/real_config.yml
--- a/.circleci/real_config.yml
+++ b/.circleci/real_config.yml
@@ -3759,10 +3759,14 @@ jobs:
             set +o pipefail
             export DET_USER=admin DET_PASS=${INITIAL_USER_PASSWORD}
             export DET_MASTER_TLS_CERT=${MASTER_TLS_CERT} DET_MASTER_CERT_NAME=${MASTER_CERT_NAME}
+            success=0
             for i in {1..10}; do
-              yes | det -m https://${MASTER_HOST}:${MASTER_PORT} user whoami | grep "logged in" && break || \
+              yes | det -m https://${MASTER_HOST}:${MASTER_PORT} user whoami | grep "logged in" && success=1 && break || \
               echo "Trying to connect to master host again in 5 seconds" && sleep 5
             done
+            if [ "$success" -eq 0 ]; then
+              echo "Failed to connect to master host" && exit 1
+            fi
       - run-e2e-tests:
           mark: <<parameters.mark>>
           master-host: ${MASTER_HOST}
