selective gco

diff --git a/harness/determined/deploy/aws/templates/lore.yaml b/harness/determined/deploy/aws/templates/lore.yaml
--- a/harness/determined/deploy/aws/templates/lore.yaml
+++ b/harness/determined/deploy/aws/templates/lore.yaml
@@ -101,7 +101,7 @@ Parameters:
   Version:
     Type: String
     Description: Determined version or commit for master image
-    Default: 0.26.5-dev0
+    Default: 0.27.0-dev0
 
   DBPassword:
     Type: String
@@ -216,9 +216,9 @@ Parameters:
     Description: Specifies the duration in seconds before idle notebook instances are automatically terminated.
     Default: 0
 
-  LoreVersion:
+  GenAIVersion:
     Type: String
-    Description: Lore version to deploy
+    Description: GenAI version to deploy
     Default: latest
 
   MountEFSId:
@@ -922,7 +922,7 @@ Resources:
             cpu_env_image: ${CpuEnvImage}
             gpu_env_image: ${GpuEnvImage}
             notebook_timeout: ${NotebookTimeout}
-            genai_version: ${LoreVersion}
+            genai_version: ${GenAIVersion}
 
             bind_mounts:
               - host_path: /mnt/efs
@@ -974,7 +974,7 @@ Resources:
 
             mount -t efs ${EFSVal}:/ /mnt/efs
 
-            if [ ! -z "${LoreVersion}" ]; then
+            if [ ! -z "${GenAIVersion}" ]; then
               docker run -d \
                 --name lore-backend \
                 --env DET_MASTER=http://determined-master:8080 \
@@ -983,12 +983,12 @@ Resources:
                 --env DB_PASSWORD=${DBPassword} \
                 --env DB_HOST=${Database.Endpoint.Address} \
                 --env DB_PORT=5432 \
-                --env LORE_DOCKER_TAG_SUFFIX="${LoreVersion}" \
+                --env LORE_DOCKER_TAG_SUFFIX="${GenAIVersion}" \
                 -p 9013:9013 \
                 -v /mnt/efs:/run/determined/workdir/shared_fs \
                 --network determined \
-                "determinedai/environments-dev:lore-backend-image-${LoreVersion}"
-              test $? -eq 0 || ( echo "Failed to launch lore container." && exit 1 )
+                "determinedai/environments-dev:lore-backend-image-${GenAIVersion}"
+              test $? -eq 0 || ( echo "Failed to launch GenAI container." && exit 1 )
             fi
 
             touch /usr/local/determined/etc/master.yaml
