add checks to push-shared target

diff --git a/webui/react/Makefile b/webui/react/Makefile
--- a/webui/react/Makefile
+++ b/webui/react/Makefile
@@ -82,7 +82,12 @@ test-shared:
 	cd src/shared; ./bin/test.py --repos saas --test-local
 
 .PHONY: push
-push-shared: test-shared-code
-	# CHECK should this be allowed only in core/master branch?
-	# TODO make sure changes are committed
+push-shared: test-shared
+	# fail if the branch name is not master
+	if [ "$(git rev-parse --abbrev-ref HEAD)" != "master" ]; then \
+		echo "You must be on the master branch to push to shared-web"; \
+		false; \
+	fi
+	# fail if there are uncommitted changes.
+	git diff --exit-code || (echo "uncommitted changes, please commit or stash" ; false)
 	cd ../../; git subtree push --prefix=webui/react/src/shared https://github.com/determined-ai/shared-web main
